"""Generate CRUD pytest tests for core entities.

This script is intentionally simple: it emits a single pytest file with tests
for Patient, Dossier, Venue, Mouvement, EntiteJuridique and EntiteGeographique.
Generated tests rely on existing fixtures: `client`, `session`, and helpers in
`tests/conftest.py`.

Run:
    python scripts/generate_crud_tests.py

"""
from datetime import datetime
from pathlib import Path

def main():
    out = Path("tests/generated/test_crud_generated.py")
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("from fastapi.testclient import TestClient")
    lines.append("from sqlmodel import select")
    lines.append("from app.models import Patient, Dossier, Venue, Mouvement")
    lines.append("from app.models_structure import EntiteJuridique, EntiteGeographique")
    lines.append("from app.db import get_next_sequence")
    lines.append("")
    lines.append("def test_patient_crud(client: TestClient, session):")
    lines.append("    # create")
    lines.append("    payload = {'family': 'GEN', 'given': 'Alice', 'gender': 'female', 'birth_date': '1990-01-01'}")
    lines.append("    r = client.post('/patients/new', data=payload, follow_redirects=True)")
    lines.append("    assert r.status_code in (200, 303)")
    lines.append("    # find in db")
    lines.append("    p = session.exec(select(Patient).where(Patient.family == 'GEN')).first()")
    lines.append("    assert p is not None")
    lines.append("    # edit")
    lines.append("    r2 = client.post(f'/patients/{p.id}/edit', data={'family': 'GEN2', 'given': p.given}, follow_redirects=True)")
    lines.append("    assert r2.status_code in (200, 303)")
    lines.append("    session.expire_all()")
    lines.append("    p2 = session.get(Patient, p.id)")
    lines.append("    assert p2.family == 'GEN2'")
    lines.append("    # delete")
    lines.append("    r3 = client.post(f'/patients/{p.id}/delete', follow_redirects=True)")
    lines.append("    assert r3.status_code in (200, 303)")
    lines.append("")
    # Dossier CRUD
    lines.append("def test_dossier_crud(client: TestClient, session):")
    lines.append("    # need a patient in db")
    lines.append("    seq = get_next_sequence(session, 'patient')")
    lines.append("    p = Patient(patient_seq=seq, family='DOSP', given='Ui', gender='other')")
    lines.append("    session.add(p); session.commit(); session.refresh(p)")
    lines.append("    # set patient context via client")
    lines.append("    client.get(f'/context/patient/{p.id}', follow_redirects=True)")
    lines.append("    now = datetime.now().strftime('%Y-%m-%dT%H:%M')")
    lines.append("    payload = {'patient_id': str(p.id), 'admit_time': now}")
    lines.append("    r = client.post('/dossiers/new', data=payload, follow_redirects=False)")
    lines.append("    assert r.status_code in (302, 303)")
    lines.append("    d = session.exec(select(Dossier).where(Dossier.patient_id == p.id)).first()")
    lines.append("    assert d is not None")
    lines.append("    # edit dossier")
    lines.append("    r2 = client.post(f'/dossiers/{d.id}/edit', data={'patient_id': p.id, 'uf_responsabilite': d.uf_responsabilite or '', 'dossier_type': str(d.dossier_type.value if d.dossier_type else 'hospitalise'), 'admit_time': d.admit_time.strftime('%Y-%m-%dT%H:%M'), 'dossier_seq': d.dossier_seq}, follow_redirects=True)")
    lines.append("    assert r2.status_code in (200, 303)")
    lines.append("    # delete")
    lines.append("    r3 = client.post(f'/dossiers/{d.id}/delete', follow_redirects=True)")
    lines.append("    assert r3.status_code in (200, 303)")
    lines.append("")
    # Venue CRUD (requires a dossier)
    lines.append("def test_venue_crud(client: TestClient, session):")
    lines.append("    seq = get_next_sequence(session, 'patient')")
    lines.append("    patient = Patient(patient_seq=seq, family='VUDP', given='Ui')")
    lines.append("    session.add(patient); session.commit(); session.refresh(patient)")
    lines.append("    # create dossier")
    lines.append("    from datetime import datetime as _dt")
    lines.append("    now = _dt.now().strftime('%Y-%m-%dT%H:%M')")
    lines.append("    client.get(f'/context/patient/{patient.id}', follow_redirects=True)")
    lines.append("    payload = {'patient_id': str(patient.id), 'admit_time': now}")
    lines.append("    client.post('/dossiers/new', data=payload, follow_redirects=False)")
    lines.append("    d = session.exec(select(Dossier).where(Dossier.patient_id == patient.id)).first()")
    lines.append("    assert d is not None")
    lines.append("    # create venue")
    lines.append("    payload2 = {'dossier_id': str(d.id), 'uf_responsabilite': '', 'start_time': now}")
    lines.append("    r = client.post('/venues/new', data=payload2, follow_redirects=True)")
    lines.append("    assert r.status_code in (200, 303)")
    lines.append("    v = session.exec(select(Venue).where(Venue.dossier_id == d.id)).first()")
    lines.append("    assert v is not None")
    lines.append("    # edit venue")
    lines.append("    r2 = client.post(f'/venues/{v.id}/edit', data={'dossier_id': d.id, 'uf_responsabilite': v.uf_responsabilite or '', 'start_time': v.start_time.strftime('%Y-%m-%dT%H:%M'), 'venue_seq': v.venue_seq}, follow_redirects=True)")
    lines.append("    assert r2.status_code in (200, 303)")
    lines.append("    # delete")
    lines.append("    r3 = client.post(f'/venues/{v.id}/delete', follow_redirects=True)")
    lines.append("    assert r3.status_code in (200, 303)")
    lines.append("")
    # Mouvement CRUD (requires a venue)
    lines.append("def test_mouvement_crud(client: TestClient, session):")
    lines.append("    # create patient/dossier/venue similar to venue test")
    lines.append("    seq = get_next_sequence(session, 'patient')")
    lines.append("    patient = Patient(patient_seq=seq, family='MOUV', given='Ui')")
    lines.append("    session.add(patient); session.commit(); session.refresh(patient)")
    lines.append("    from datetime import datetime as _dt")
    lines.append("    now = _dt.now().strftime('%Y-%m-%dT%H:%M')")
    lines.append("    client.get(f'/context/patient/{patient.id}', follow_redirects=True)")
    lines.append("    payload = {'patient_id': str(patient.id), 'admit_time': now}")
    lines.append("    client.post('/dossiers/new', data=payload, follow_redirects=False)")
    lines.append("    d = session.exec(select(Dossier).where(Dossier.patient_id == patient.id)).first()")
    lines.append("    # create venue")
    lines.append("    payload2 = {'dossier_id': str(d.id), 'uf_responsabilite': '', 'start_time': now}")
    lines.append("    client.post('/venues/new', data=payload2, follow_redirects=True)")
    lines.append("    v = session.exec(select(Venue).where(Venue.dossier_id == d.id)).first()")
    lines.append("    # create mouvement (A01 admission)")
    lines.append("    mouvement_payload = {'venue_id': str(v.id), 'type': 'ADT^A01', 'when': now}")
    lines.append("    r = client.post('/mouvements/new', data=mouvement_payload, follow_redirects=True)")
    lines.append("    assert r.status_code in (200, 303, 302)")
    lines.append("    m = session.exec(select(Mouvement).where(Mouvement.venue_id == v.id)).first()")
    lines.append("    assert m is not None")
    lines.append("    # edit mouvement (via edit form) - simply get edit page and post similar data")
    lines.append("    r2 = client.get(f'/mouvements/{m.id}/edit')")
    lines.append("    assert r2.status_code == 200")
    lines.append("    r3 = client.post(f'/mouvements/{m.id}/edit', data={'venue_id': v.id, 'type': m.type or 'ADT^A01', 'when': now, 'mouvement_seq': m.mouvement_seq}, follow_redirects=True)")
    lines.append("    # delete mouvement")
    lines.append("    r4 = client.post(f'/mouvements/{m.id}/delete', follow_redirects=True)")
    lines.append("    # note: some delete endpoints may return 404 or redirect, accept both")
    lines.append("    assert r4.status_code in (200, 303, 404)")
    lines.append("")
    # Structure CRUD: EntiteGeographique + EntiteJuridique
    lines.append("def test_structure_ej_eg_crud(client: TestClient, session):")
    lines.append("    # create EJ via model (simpler) and then use api endpoints for EG")
    lines.append("    ej = EntiteJuridique(name='EJ-GEN', finess_ej='123456778', is_active=True)")
    lines.append("    session.add(ej); session.commit(); session.refresh(ej)")
    lines.append("    # create EG via POST /structure/eg")
    lines.append("    payload = {'name': 'EG Test', 'identifier': 'EG-1', 'finess': 'F-1'}")
    lines.append("    r = client.post('/structure/eg', json=payload)")
    lines.append("    assert r.status_code == 200")
    lines.append("    eg = session.exec(select(EntiteGeographique).where(EntiteGeographique.name == 'EG Test')).first()")
    lines.append("    assert eg is not None")
    lines.append("    # view and edit EG")
    lines.append("    r2 = client.get(f'/structure/eg/{eg.id}')")
    lines.append("    assert r2.status_code == 200")
    lines.append("    r3 = client.post(f'/structure/eg/{eg.id}', data={'name': 'EG Test Updated'})")
    lines.append("    assert r3.status_code in (200, 303)")
    lines.append("    # delete EG")
    lines.append("    r4 = client.post(f'/structure/eg/{eg.id}/delete')")
    lines.append("    assert r4.status_code in (200, 303)")

    out.write_text('\n'.join(lines))
    print('Generated', out)

if __name__ == '__main__':
    main()
