from fastapi import APIRouter, UploadFile, File, Form, Depends, HTTPException
from sqlmodel import Session
from app.db import get_session
from app.models_structure import GHTContext, EntiteJuridique
from pathlib import Path
import tempfile
import importlib.util
from functools import lru_cache
import logging
from uuid import uuid4

from config.settings import settings

router = APIRouter(prefix="/import", tags=["import"])
logger = logging.getLogger(__name__)
UPLOAD_CHUNK_SIZE = 64 * 1024

@lru_cache(maxsize=1)
def _load_import_impls():
    """Charge dynamiquement les implémentations d'import depuis l'outil existant."""
    project_root = Path(__file__).resolve().parents[2]
    script_path = project_root / "scripts" / "tools" / "import_test_exemples.py"

    if not script_path.exists():
        raise RuntimeError(f"Script d'import introuvable: {script_path}")

    module_name = "import_test_exemples_runtime"
    spec = importlib.util.spec_from_file_location(module_name, script_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Impossible de charger le module d'import: {script_path}")

    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    import_structure = getattr(module, "import_structure_mfn", None)
    import_pam = getattr(module, "import_pam_messages", None)
    if import_structure is None or import_pam is None:
        raise RuntimeError("Fonctions d'import MFN/PAM introuvables dans le script d'import")

    return import_structure, import_pam


def _resolve_ej_in_ght(session: Session, ght_id: int, ej_id: int) -> EntiteJuridique:
    """Valide que l'EJ existe et appartient bien au GHT fourni."""
    ght = session.get(GHTContext, ght_id)
    if not ght:
        raise HTTPException(status_code=404, detail=f"GHT {ght_id} introuvable")

    ej = session.get(EntiteJuridique, ej_id)
    if not ej:
        raise HTTPException(status_code=404, detail=f"Entité juridique {ej_id} introuvable")

    if ej.ght_context_id != ght_id:
        raise HTTPException(
            status_code=400,
            detail=f"L'entité juridique {ej_id} n'appartient pas au GHT {ght_id}",
        )

    return ej


def _resolve_ej(session: Session, ej_id: int) -> EntiteJuridique:
    """Valide que l'EJ existe."""
    ej = session.get(EntiteJuridique, ej_id)
    if not ej:
        raise HTTPException(status_code=404, detail=f"Entité juridique {ej_id} introuvable")
    return ej


def _safe_pam_upload_destination(tmpdir: Path, filename: str) -> Path:
    """Return a server-generated path for a PAM upload inside ``tmpdir``.

    A multipart filename is client-controlled metadata.  It must never be used
    as a filesystem path: both POSIX and Windows separators are rejected and
    the on-disk name is generated by the server.
    """
    basename = Path(filename).name
    if (
        not filename
        or basename != filename
        or "/" in filename
        or "\\" in filename
        or "\x00" in filename
    ):
        raise HTTPException(status_code=400, detail="Nom de fichier PAM invalide")
    if not filename.lower().endswith(".hl7"):
        raise HTTPException(
            status_code=400,
            detail=f"Extension non supportée pour {filename} (attendu .hl7)",
        )

    root = tmpdir.resolve()
    destination = (root / f"{uuid4().hex}.hl7").resolve()
    if destination.parent != root:
        raise RuntimeError("Destination temporaire PAM invalide")
    return destination


def _read_upload_limited(source, max_size: int) -> bytes:
    """Read an upload in bounded chunks and reject it at the first excess byte."""
    content = bytearray()
    while True:
        remaining = max_size + 1 - len(content)
        if remaining <= 0:
            raise HTTPException(status_code=413, detail="Fichier trop volumineux")
        chunk = source.read(min(UPLOAD_CHUNK_SIZE, remaining))
        if not chunk:
            return bytes(content)
        content.extend(chunk)

@router.post("/structure_mfn/")
def import_structure_mfn_endpoint(
    ght_id: int = Form(...),
    ej_id: int = Form(...),
    file: UploadFile = File(...),
    session: Session = Depends(get_session)
):
    """Importe une structure MFN via upload."""
    if not file.filename:
        raise HTTPException(status_code=400, detail="Nom de fichier MFN manquant")

    max_size = settings.max_upload_size_mb * 1024 * 1024
    file_bytes = _read_upload_limited(file.file, max_size)
    if len(file_bytes) == 0:
        raise HTTPException(status_code=400, detail="Fichier MFN vide")

    ej = _resolve_ej_in_ght(session, ght_id, ej_id)
    import_structure_mfn_impl, _ = _load_import_impls()

    with tempfile.NamedTemporaryFile(delete=False, suffix=".hl7") as tmp:
        tmp.write(file_bytes)
        tmp_path = Path(tmp.name)

    try:
        import_structure_mfn_impl(session, ej, tmp_path)
    except HTTPException:
        raise
    except Exception as exc:
        logger.error("Structure MFN import failed: %s", type(exc).__name__)
        raise HTTPException(
            status_code=500,
            detail="Erreur interne pendant l'import de structure MFN",
        ) from exc
    finally:
        tmp_path.unlink(missing_ok=True)

    return {
        "status": "ok",
        "type": "structure_mfn",
        "ght_id": ght_id,
        "ej_id": ej_id,
        "filename": file.filename,
        "bytes": len(file_bytes),
    }

@router.post("/pam_messages/")
def import_pam_messages_endpoint(
    ej_id: int = Form(...),
    files: list[UploadFile] = File(...),
    session: Session = Depends(get_session)
):
    """Importe des messages PAM HL7 via upload."""
    if not files:
        raise HTTPException(status_code=400, detail="Aucun fichier PAM fourni")

    ej = _resolve_ej(session, ej_id)
    _, import_pam_messages_impl = _load_import_impls()

    max_size = settings.max_upload_size_mb * 1024 * 1024
    imported_filenames: list[str] = []

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir_path = Path(tmpdir)
        for file in files:
            if not file.filename:
                raise HTTPException(status_code=400, detail="Un fichier PAM n'a pas de nom")
            file_path = _safe_pam_upload_destination(tmpdir_path, file.filename)

            content = _read_upload_limited(file.file, max_size)
            if len(content) == 0:
                raise HTTPException(status_code=400, detail=f"Fichier PAM vide: {file.filename}")

            with open(file_path, "xb") as f:
                f.write(content)
            imported_filenames.append(file.filename)

        try:
            imported_count = import_pam_messages_impl(session, ej, tmpdir_path, max_files=len(imported_filenames))
        except HTTPException:
            raise
        except Exception as exc:
            logger.error("PAM messages import failed: %s", type(exc).__name__)
            raise HTTPException(
                status_code=500,
                detail="Erreur interne pendant l'import des messages PAM",
            ) from exc

    return {
        "status": "ok",
        "type": "pam_messages",
        "ej_id": ej_id,
        "files_received": len(imported_filenames),
        "files": imported_filenames,
        "messages_imported": imported_count,
    }
