"""add_hprim_complete_fields_to_cotations

Revision ID: bd558aad6d90
Revises: db86856c4965
Create Date: 2026-01-08 06:40:06.965793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bd558aad6d90'
down_revision: Union[str, Sequence[str], None] = 'db86856c4965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Commenté: ces tables ne devraient pas être supprimées
    # op.drop_table('patient_fts_config')
    # op.drop_table('patient_fts_idx')
    # op.drop_table('patient_fts_data')
    # op.drop_index('ix_scenario_ej_config_entite_juridique_id', table_name='scenario_ej_config')
    # op.drop_table('scenario_ej_config')
    # op.drop_table('patient_fts')
    # op.drop_table('patient_fts_docsize')
    op.add_column('ccamact', sa.Column('identifiant_acte', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('code_acte_extension_pmsi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('code_association_non_prevue', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('code_extension_documentaire', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('positions_dentaires', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('montant_total', sa.Float(), nullable=True))
    op.add_column('ccamact', sa.Column('montant_depassement', sa.Float(), nullable=True))
    op.add_column('ccamact', sa.Column('motif_depassement', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('numero_forfait_technique', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('numero_facture', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('risque', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('entente_prealable', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('indicateur_parcours_soins', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('date_demande_accord', sa.Date(), nullable=True))
    op.add_column('ccamact', sa.Column('identifiant_acte_principal', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('code_acte_principal', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('radiotherapie_seances', sa.Integer(), nullable=True))
    op.add_column('ccamact', sa.Column('radiotherapie_modalite', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('ccamact', sa.Column('rapport_exoneration', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('remboursement_exceptionnel', sa.Boolean(), nullable=False))
    op.add_column('ccamact', sa.Column('supplement_charges', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('pmsi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('documentaire', sa.Boolean(), nullable=False))
    op.add_column('ccamact', sa.Column('gratuit', sa.Boolean(), nullable=False))
    op.add_column('ccamact', sa.Column('option_coordination', sa.Boolean(), nullable=False))
    op.add_column('ccamact', sa.Column('prevention_amo_amc', sa.Boolean(), nullable=False))
    op.add_column('ccamact', sa.Column('forfait_securite_environnement', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('signe', sa.Boolean(), nullable=False))
    op.add_column('ccamact', sa.Column('exoneration_ccam', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('mode_traitement', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('discipline_traitement', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ccamact', sa.Column('liberal', sa.Boolean(), nullable=False))
    op.add_column('ccamact', sa.Column('date_action', sa.DateTime(), nullable=True))
    op.add_column('ccamact', sa.Column('acteur_id', sa.Integer(), nullable=True))
    op.alter_column('ccamact', 'code_phase',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ccamact', 'modificateurs',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ccamact', 'quantite',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ccamact', 'facture',
               existing_type=sa.BOOLEAN(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_column('ccamact', 'execute_heure')
    op.drop_column('ccamact', 'montant')
    op.drop_column('ccamact', 'extension')
    op.add_column('dossier', sa.Column('has_cotations', sa.Boolean(), nullable=False))
    op.add_column('dossier', sa.Column('cotations_count', sa.Integer(), nullable=False))
    op.drop_index('idx_dossier_patient_id', table_name='dossier')
    op.create_foreign_key(None, 'identifiernamespace', 'service', ['service_id'], ['id'])
    op.create_foreign_key(None, 'identifiernamespace', 'entitegeographique', ['entite_geographique_id'], ['id'])
    op.create_foreign_key(None, 'identifiernamespace', 'lit', ['lit_id'], ['id'])
    op.create_foreign_key(None, 'identifiernamespace', 'unitefonctionnelle', ['unite_fonctionnelle_id'], ['id'])
    op.create_foreign_key(None, 'identifiernamespace', 'chambre', ['chambre_id'], ['id'])
    op.create_foreign_key(None, 'identifiernamespace', 'pole', ['pole_id'], ['id'])
    op.create_foreign_key(None, 'identifiernamespace', 'unitehebergement', ['unite_hebergement_id'], ['id'])
    op.add_column('lppact', sa.Column('identifiant_acte', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lppact', sa.Column('code_interne_lpp', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lppact', sa.Column('code_commercial_lpp', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lppact', sa.Column('denomination_libelle', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('lppact', sa.Column('siret_fournisseur', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lppact', sa.Column('identifiant_fournisseur_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lppact', sa.Column('identifiant_fournisseur_libelle', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lppact', sa.Column('taux_tva', sa.Float(), nullable=True))
    op.add_column('lppact', sa.Column('montant_unitaire_achat_ttc', sa.Float(), nullable=True))
    op.add_column('lppact', sa.Column('montant_ecart_indemnisable', sa.Float(), nullable=True))
    op.add_column('lppact', sa.Column('montant_unitaire_facture_ttc', sa.Float(), nullable=False))
    op.add_column('lppact', sa.Column('risque', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lppact', sa.Column('entente_prealable', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lppact', sa.Column('indicateur_parcours_soins', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lppact', sa.Column('date_demande_accord', sa.Date(), nullable=True))
    op.add_column('lppact', sa.Column('date_peremption', sa.Date(), nullable=True))
    op.add_column('lppact', sa.Column('numero_serie', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lppact', sa.Column('numero_lot', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lppact', sa.Column('iud_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lppact', sa.Column('nature_prestation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('lppact', sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('lppact', sa.Column('gratuit', sa.Boolean(), nullable=False))
    op.add_column('lppact', sa.Column('liberal', sa.Boolean(), nullable=False))
    op.add_column('lppact', sa.Column('signe', sa.Boolean(), nullable=False))
    op.add_column('lppact', sa.Column('date_action', sa.DateTime(), nullable=True))
    op.add_column('lppact', sa.Column('acteur_id', sa.Integer(), nullable=True))
    op.add_column('lppact', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('lppact', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('lppact', 'code_lpp',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('lppact', 'facture',
               existing_type=sa.BOOLEAN(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_column('lppact', 'prix_unitaire')
    op.drop_column('lppact', 'libelle')
    op.drop_column('lppact', 'montant_total')
    op.drop_index('idx_messagelog_status_endpoint_created', table_name='messagelog')
    op.drop_index('idx_mouvement_venue_when', table_name='mouvement')
    op.drop_index('idx_mouvement_when', table_name='mouvement')
    op.add_column('ngapact', sa.Column('identifiant_acte', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ngapact', sa.Column('quantite', sa.Integer(), nullable=True))
    op.add_column('ngapact', sa.Column('nabm_codes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ngapact', sa.Column('majoration_pourcentage', sa.Integer(), nullable=True))
    op.add_column('ngapact', sa.Column('majoration_coefficient', sa.Float(), nullable=True))
    op.add_column('ngapact', sa.Column('minoration_pourcentage', sa.Integer(), nullable=True))
    op.add_column('ngapact', sa.Column('minoration_coefficient', sa.Float(), nullable=True))
    op.add_column('ngapact', sa.Column('risque', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ngapact', sa.Column('entente_prealable', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ngapact', sa.Column('indicateur_parcours_soins', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ngapact', sa.Column('date_demande_accord', sa.Date(), nullable=True))
    op.add_column('ngapact', sa.Column('montant_total', sa.Float(), nullable=True))
    op.add_column('ngapact', sa.Column('montant_depassement', sa.Float(), nullable=True))
    op.add_column('ngapact', sa.Column('motif_depassement', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ngapact', sa.Column('numero_facture', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ngapact', sa.Column('bhn_phn_montant', sa.Float(), nullable=True))
    op.add_column('ngapact', sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('ngapact', sa.Column('execution_nuit', sa.Boolean(), nullable=False))
    op.add_column('ngapact', sa.Column('execution_dimanche_ferie', sa.Boolean(), nullable=False))
    op.add_column('ngapact', sa.Column('acte_hors_nomenclature', sa.Boolean(), nullable=False))
    op.add_column('ngapact', sa.Column('rapport_exoneration', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ngapact', sa.Column('gratuit', sa.Boolean(), nullable=False))
    op.add_column('ngapact', sa.Column('portee_cle', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('ngapact', sa.Column('activite_recherche', sa.Boolean(), nullable=False))
    op.add_column('ngapact', sa.Column('code_prestation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ngapact', sa.Column('date_action', sa.DateTime(), nullable=True))
    op.add_column('ngapact', sa.Column('acteur_id', sa.Integer(), nullable=True))
    op.add_column('ngapact', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('ngapact', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('ngapact', 'facture',
               existing_type=sa.BOOLEAN(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_column('ngapact', 'execute_heure')
    op.drop_column('ngapact', 'montant')
    op.drop_index('idx_patient_entite_juridique', table_name='patient')
    op.drop_index('idx_patient_family', table_name='patient')
    op.drop_index('idx_patient_ght_context', table_name='patient')
    op.drop_index('idx_patient_given', table_name='patient')
    op.drop_index('idx_patient_identifier', table_name='patient')
    op.add_column('systemendpoint', sa.Column('ack_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('systemendpoint', sa.Column('ftp_remote_ack_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ucdact', sa.Column('identifiant_acte', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ucdact', sa.Column('code_interne_ucd', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ucdact', sa.Column('code_ucd', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('ucdact', sa.Column('code_commercial', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ucdact', sa.Column('denomination_libelle', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('ucdact', sa.Column('denomination_dosage', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ucdact', sa.Column('denomination_forme', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ucdact', sa.Column('nature_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ucdact', sa.Column('taux_tva', sa.Float(), nullable=True))
    op.add_column('ucdact', sa.Column('montant_unitaire_achat_ttc', sa.Float(), nullable=True))
    op.add_column('ucdact', sa.Column('montant_unitaire_achat_ht', sa.Float(), nullable=True))
    op.add_column('ucdact', sa.Column('montant_ecart_indemnisable', sa.Float(), nullable=True))
    op.add_column('ucdact', sa.Column('montant_unitaire_facture_ttc', sa.Float(), nullable=True))
    op.add_column('ucdact', sa.Column('montant_unitaire_facture_ht', sa.Float(), nullable=True))
    op.add_column('ucdact', sa.Column('montant_marge_retrocession', sa.Float(), nullable=True))
    op.add_column('ucdact', sa.Column('montant_reconstitution', sa.Float(), nullable=True))
    op.add_column('ucdact', sa.Column('risque', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ucdact', sa.Column('entente_prealable', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ucdact', sa.Column('indicateur_parcours_soins', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ucdact', sa.Column('date_demande_accord', sa.Date(), nullable=True))
    op.add_column('ucdact', sa.Column('nature_prestation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ucdact', sa.Column('siret_fournisseur', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ucdact', sa.Column('numero_lot', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ucdact', sa.Column('code_indication_les', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ucdact', sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('ucdact', sa.Column('gratuit', sa.Boolean(), nullable=False))
    op.add_column('ucdact', sa.Column('liberal', sa.Boolean(), nullable=False))
    op.add_column('ucdact', sa.Column('retrocession', sa.Boolean(), nullable=False))
    op.add_column('ucdact', sa.Column('essai_therapeutique', sa.Boolean(), nullable=False))
    op.add_column('ucdact', sa.Column('prescripteur_id', sa.Integer(), nullable=True))
    op.add_column('ucdact', sa.Column('date_action', sa.DateTime(), nullable=True))
    op.add_column('ucdact', sa.Column('acteur_id', sa.Integer(), nullable=True))
    op.add_column('ucdact', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('ucdact', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('ucdact', 'quantite',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ucdact', 'facture',
               existing_type=sa.BOOLEAN(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.create_foreign_key(None, 'ucdact', 'medecinresponsable', ['prescripteur_id'], ['id'])
    op.drop_column('ucdact', 'code_cip')
    op.drop_column('ucdact', 'designation')
    op.drop_column('ucdact', 'prix_unitaire')
    op.drop_column('ucdact', 'montant_total')
    op.drop_index('idx_venue_dossier', table_name='venue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_venue_dossier', 'venue', ['dossier_id'], unique=False)
    op.add_column('ucdact', sa.Column('montant_total', sa.FLOAT(), nullable=False))
    op.add_column('ucdact', sa.Column('prix_unitaire', sa.FLOAT(), nullable=False))
    op.add_column('ucdact', sa.Column('designation', sa.VARCHAR(), nullable=False))
    op.add_column('ucdact', sa.Column('code_cip', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'ucdact', type_='foreignkey')
    op.alter_column('ucdact', 'facture',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.alter_column('ucdact', 'quantite',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('ucdact', 'updated_at')
    op.drop_column('ucdact', 'created_at')
    op.drop_column('ucdact', 'acteur_id')
    op.drop_column('ucdact', 'date_action')
    op.drop_column('ucdact', 'prescripteur_id')
    op.drop_column('ucdact', 'essai_therapeutique')
    op.drop_column('ucdact', 'retrocession')
    op.drop_column('ucdact', 'liberal')
    op.drop_column('ucdact', 'gratuit')
    op.drop_column('ucdact', 'action')
    op.drop_column('ucdact', 'code_indication_les')
    op.drop_column('ucdact', 'numero_lot')
    op.drop_column('ucdact', 'siret_fournisseur')
    op.drop_column('ucdact', 'nature_prestation')
    op.drop_column('ucdact', 'date_demande_accord')
    op.drop_column('ucdact', 'indicateur_parcours_soins')
    op.drop_column('ucdact', 'entente_prealable')
    op.drop_column('ucdact', 'risque')
    op.drop_column('ucdact', 'montant_reconstitution')
    op.drop_column('ucdact', 'montant_marge_retrocession')
    op.drop_column('ucdact', 'montant_unitaire_facture_ht')
    op.drop_column('ucdact', 'montant_unitaire_facture_ttc')
    op.drop_column('ucdact', 'montant_ecart_indemnisable')
    op.drop_column('ucdact', 'montant_unitaire_achat_ht')
    op.drop_column('ucdact', 'montant_unitaire_achat_ttc')
    op.drop_column('ucdact', 'taux_tva')
    op.drop_column('ucdact', 'nature_date')
    op.drop_column('ucdact', 'denomination_forme')
    op.drop_column('ucdact', 'denomination_dosage')
    op.drop_column('ucdact', 'denomination_libelle')
    op.drop_column('ucdact', 'code_commercial')
    op.drop_column('ucdact', 'code_ucd')
    op.drop_column('ucdact', 'code_interne_ucd')
    op.drop_column('ucdact', 'identifiant_acte')
    op.drop_column('systemendpoint', 'ftp_remote_ack_path')
    op.drop_column('systemendpoint', 'ack_path')
    op.create_index('idx_patient_identifier', 'patient', ['identifier'], unique=False)
    op.create_index('idx_patient_given', 'patient', ['given'], unique=False)
    op.create_index('idx_patient_ght_context', 'patient', ['ght_context_id'], unique=False)
    op.create_index('idx_patient_family', 'patient', ['family'], unique=False)
    op.create_index('idx_patient_entite_juridique', 'patient', ['entite_juridique_id'], unique=False)
    op.add_column('ngapact', sa.Column('montant', sa.FLOAT(), nullable=True))
    op.add_column('ngapact', sa.Column('execute_heure', sa.VARCHAR(), nullable=True))
    op.alter_column('ngapact', 'facture',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.drop_column('ngapact', 'updated_at')
    op.drop_column('ngapact', 'created_at')
    op.drop_column('ngapact', 'acteur_id')
    op.drop_column('ngapact', 'date_action')
    op.drop_column('ngapact', 'code_prestation')
    op.drop_column('ngapact', 'activite_recherche')
    op.drop_column('ngapact', 'portee_cle')
    op.drop_column('ngapact', 'gratuit')
    op.drop_column('ngapact', 'rapport_exoneration')
    op.drop_column('ngapact', 'acte_hors_nomenclature')
    op.drop_column('ngapact', 'execution_dimanche_ferie')
    op.drop_column('ngapact', 'execution_nuit')
    op.drop_column('ngapact', 'action')
    op.drop_column('ngapact', 'bhn_phn_montant')
    op.drop_column('ngapact', 'numero_facture')
    op.drop_column('ngapact', 'motif_depassement')
    op.drop_column('ngapact', 'montant_depassement')
    op.drop_column('ngapact', 'montant_total')
    op.drop_column('ngapact', 'date_demande_accord')
    op.drop_column('ngapact', 'indicateur_parcours_soins')
    op.drop_column('ngapact', 'entente_prealable')
    op.drop_column('ngapact', 'risque')
    op.drop_column('ngapact', 'minoration_coefficient')
    op.drop_column('ngapact', 'minoration_pourcentage')
    op.drop_column('ngapact', 'majoration_coefficient')
    op.drop_column('ngapact', 'majoration_pourcentage')
    op.drop_column('ngapact', 'nabm_codes')
    op.drop_column('ngapact', 'quantite')
    op.drop_column('ngapact', 'identifiant_acte')
    op.create_index('idx_mouvement_when', 'mouvement', ['when'], unique=False)
    op.create_index('idx_mouvement_venue_when', 'mouvement', ['venue_id', 'when'], unique=False)
    op.create_index('idx_messagelog_status_endpoint_created', 'messagelog', ['status', 'endpoint_id', 'created_at'], unique=False)
    op.add_column('lppact', sa.Column('montant_total', sa.FLOAT(), nullable=False))
    op.add_column('lppact', sa.Column('libelle', sa.VARCHAR(), nullable=False))
    op.add_column('lppact', sa.Column('prix_unitaire', sa.FLOAT(), nullable=False))
    op.alter_column('lppact', 'facture',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.alter_column('lppact', 'code_lpp',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('lppact', 'updated_at')
    op.drop_column('lppact', 'created_at')
    op.drop_column('lppact', 'acteur_id')
    op.drop_column('lppact', 'date_action')
    op.drop_column('lppact', 'signe')
    op.drop_column('lppact', 'liberal')
    op.drop_column('lppact', 'gratuit')
    op.drop_column('lppact', 'action')
    op.drop_column('lppact', 'nature_prestation')
    op.drop_column('lppact', 'iud_id')
    op.drop_column('lppact', 'numero_lot')
    op.drop_column('lppact', 'numero_serie')
    op.drop_column('lppact', 'date_peremption')
    op.drop_column('lppact', 'date_demande_accord')
    op.drop_column('lppact', 'indicateur_parcours_soins')
    op.drop_column('lppact', 'entente_prealable')
    op.drop_column('lppact', 'risque')
    op.drop_column('lppact', 'montant_unitaire_facture_ttc')
    op.drop_column('lppact', 'montant_ecart_indemnisable')
    op.drop_column('lppact', 'montant_unitaire_achat_ttc')
    op.drop_column('lppact', 'taux_tva')
    op.drop_column('lppact', 'identifiant_fournisseur_libelle')
    op.drop_column('lppact', 'identifiant_fournisseur_code')
    op.drop_column('lppact', 'siret_fournisseur')
    op.drop_column('lppact', 'denomination_libelle')
    op.drop_column('lppact', 'code_commercial_lpp')
    op.drop_column('lppact', 'code_interne_lpp')
    op.drop_column('lppact', 'identifiant_acte')
    op.drop_constraint(None, 'identifiernamespace', type_='foreignkey')
    op.drop_constraint(None, 'identifiernamespace', type_='foreignkey')
    op.drop_constraint(None, 'identifiernamespace', type_='foreignkey')
    op.drop_constraint(None, 'identifiernamespace', type_='foreignkey')
    op.drop_constraint(None, 'identifiernamespace', type_='foreignkey')
    op.drop_constraint(None, 'identifiernamespace', type_='foreignkey')
    op.drop_constraint(None, 'identifiernamespace', type_='foreignkey')
    op.create_index('idx_dossier_patient_id', 'dossier', ['patient_id'], unique=False)
    op.drop_column('dossier', 'cotations_count')
    op.drop_column('dossier', 'has_cotations')
    op.add_column('ccamact', sa.Column('extension', sa.VARCHAR(), nullable=True))
    op.add_column('ccamact', sa.Column('montant', sa.FLOAT(), nullable=True))
    op.add_column('ccamact', sa.Column('execute_heure', sa.VARCHAR(), nullable=True))
    op.alter_column('ccamact', 'facture',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.alter_column('ccamact', 'quantite',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ccamact', 'modificateurs',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ccamact', 'code_phase',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('ccamact', 'acteur_id')
    op.drop_column('ccamact', 'date_action')
    op.drop_column('ccamact', 'liberal')
    op.drop_column('ccamact', 'discipline_traitement')
    op.drop_column('ccamact', 'mode_traitement')
    op.drop_column('ccamact', 'exoneration_ccam')
    op.drop_column('ccamact', 'signe')
    op.drop_column('ccamact', 'forfait_securite_environnement')
    op.drop_column('ccamact', 'prevention_amo_amc')
    op.drop_column('ccamact', 'option_coordination')
    op.drop_column('ccamact', 'gratuit')
    op.drop_column('ccamact', 'documentaire')
    op.drop_column('ccamact', 'pmsi')
    op.drop_column('ccamact', 'supplement_charges')
    op.drop_column('ccamact', 'remboursement_exceptionnel')
    op.drop_column('ccamact', 'rapport_exoneration')
    op.drop_column('ccamact', 'action')
    op.drop_column('ccamact', 'radiotherapie_modalite')
    op.drop_column('ccamact', 'radiotherapie_seances')
    op.drop_column('ccamact', 'code_acte_principal')
    op.drop_column('ccamact', 'identifiant_acte_principal')
    op.drop_column('ccamact', 'date_demande_accord')
    op.drop_column('ccamact', 'indicateur_parcours_soins')
    op.drop_column('ccamact', 'entente_prealable')
    op.drop_column('ccamact', 'risque')
    op.drop_column('ccamact', 'numero_facture')
    op.drop_column('ccamact', 'numero_forfait_technique')
    op.drop_column('ccamact', 'motif_depassement')
    op.drop_column('ccamact', 'montant_depassement')
    op.drop_column('ccamact', 'montant_total')
    op.drop_column('ccamact', 'positions_dentaires')
    op.drop_column('ccamact', 'code_extension_documentaire')
    op.drop_column('ccamact', 'code_association_non_prevue')
    op.drop_column('ccamact', 'code_acte_extension_pmsi')
    op.drop_column('ccamact', 'identifiant_acte')
    op.create_table('patient_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_fts',
    sa.Column('family', sa.NullType(), nullable=True),
    sa.Column('given', sa.NullType(), nullable=True)
    )
    op.create_table('scenario_ej_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entite_juridique_id', sa.INTEGER(), nullable=False),
    sa.Column('uf_hospitalisation_id', sa.INTEGER(), nullable=True),
    sa.Column('chambre_hospitalisation', sa.VARCHAR(length=20), nullable=True),
    sa.Column('lit_hospitalisation', sa.VARCHAR(length=20), nullable=True),
    sa.Column('medecin_hospitalisation_rpps', sa.VARCHAR(length=11), nullable=True),
    sa.Column('medecin_hospitalisation_nom', sa.VARCHAR(length=100), nullable=True),
    sa.Column('uf_consultation_id', sa.INTEGER(), nullable=True),
    sa.Column('chambre_consultation', sa.VARCHAR(length=20), nullable=True),
    sa.Column('medecin_consultation_rpps', sa.VARCHAR(length=11), nullable=True),
    sa.Column('medecin_consultation_nom', sa.VARCHAR(length=100), nullable=True),
    sa.Column('uf_urgences_id', sa.INTEGER(), nullable=True),
    sa.Column('chambre_urgences', sa.VARCHAR(length=20), nullable=True),
    sa.Column('lit_urgences', sa.VARCHAR(length=20), nullable=True),
    sa.Column('medecin_urgences_rpps', sa.VARCHAR(length=11), nullable=True),
    sa.Column('medecin_urgences_nom', sa.VARCHAR(length=100), nullable=True),
    sa.Column('uf_mutation_cible_id', sa.INTEGER(), nullable=True),
    sa.Column('chambre_mutation', sa.VARCHAR(length=20), nullable=True),
    sa.Column('lit_mutation', sa.VARCHAR(length=20), nullable=True),
    sa.Column('medecin_mutation_rpps', sa.VARCHAR(length=11), nullable=True),
    sa.Column('medecin_mutation_nom', sa.VARCHAR(length=100), nullable=True),
    sa.Column('medecin_traitant_rpps', sa.VARCHAR(length=11), nullable=True),
    sa.Column('medecin_traitant_nom', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['entite_juridique_id'], ['entitejuridique.id'], ),
    sa.ForeignKeyConstraint(['uf_consultation_id'], ['unitefonctionnelle.id'], ),
    sa.ForeignKeyConstraint(['uf_hospitalisation_id'], ['unitefonctionnelle.id'], ),
    sa.ForeignKeyConstraint(['uf_mutation_cible_id'], ['unitefonctionnelle.id'], ),
    sa.ForeignKeyConstraint(['uf_urgences_id'], ['unitefonctionnelle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scenario_ej_config_entite_juridique_id', 'scenario_ej_config', ['entite_juridique_id'], unique=1)
    op.create_table('patient_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('patient_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    # ### end Alembic commands ###
