"""add chambre_id to venue

Revision ID: eb999a3ea3dc
Revises: 7a81d902382b
Create Date: 2025-12-20 22:00:41.408510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb999a3ea3dc'
down_revision: Union[str, Sequence[str], None] = '7a81d902382b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ajout des colonnes et clés étrangères sur venue en mode batch (compatible SQLite)
    # Les colonnes chambre_id et lit_id existent déjà, on ajoute seulement les clés étrangères
    with op.batch_alter_table('venue') as batch_op:
        batch_op.create_foreign_key('fk_venue_chambre_id', 'chambre', ['chambre_id'], ['id'])
        batch_op.create_foreign_key('fk_venue_lit_id', 'lit', ['lit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_column('venue', 'lit_id')
    op.drop_column('venue', 'chambre_id')
    op.add_column('mouvement', sa.Column('bed', sa.VARCHAR(), nullable=True))
    op.add_column('mouvement', sa.Column('room', sa.VARCHAR(), nullable=True))
    op.create_table('scenarioexecutionrun',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scenario_id', sa.INTEGER(), nullable=False),
    sa.Column('endpoint_id', sa.INTEGER(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('total_steps', sa.INTEGER(), nullable=False),
    sa.Column('success_steps', sa.INTEGER(), nullable=False),
    sa.Column('error_steps', sa.INTEGER(), nullable=False),
    sa.Column('skipped_steps', sa.INTEGER(), nullable=False),
    sa.Column('dry_run', sa.BOOLEAN(), nullable=False),
    sa.Column('options_json', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['systemendpoint.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['interopscenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarioexecutionrun_status'), 'scenarioexecutionrun', ['status'], unique=False)
    op.create_index(op.f('ix_scenarioexecutionrun_scenario_id'), 'scenarioexecutionrun', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_scenarioexecutionrun_finished_at'), 'scenarioexecutionrun', ['finished_at'], unique=False)
    op.create_index(op.f('ix_scenarioexecutionrun_endpoint_id'), 'scenarioexecutionrun', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_scenarioexecutionrun_dry_run'), 'scenarioexecutionrun', ['dry_run'], unique=False)
    op.create_table('dossiercontextmapping',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('context_id', sa.INTEGER(), nullable=False),
    sa.Column('dossier_id', sa.INTEGER(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['endpointcontext.id'], ),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endpointcontext',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('endpoint_id', sa.INTEGER(), nullable=False),
    sa.Column('last_sequence_value', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['systemendpoint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarioexecutionsteplog',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.Column('step_id', sa.INTEGER(), nullable=True),
    sa.Column('endpoint_id', sa.INTEGER(), nullable=True),
    sa.Column('order_index', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('ack_code', sa.VARCHAR(), nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), nullable=True),
    sa.Column('error_message', sa.VARCHAR(), nullable=True),
    sa.Column('payload_excerpt', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['systemendpoint.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['scenarioexecutionrun.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['interopscenariostep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarioexecutionsteplog_step_id'), 'scenarioexecutionsteplog', ['step_id'], unique=False)
    op.create_index(op.f('ix_scenarioexecutionsteplog_status'), 'scenarioexecutionsteplog', ['status'], unique=False)
    op.create_index(op.f('ix_scenarioexecutionsteplog_run_id'), 'scenarioexecutionsteplog', ['run_id'], unique=False)
    op.create_index(op.f('ix_scenarioexecutionsteplog_order_index'), 'scenarioexecutionsteplog', ['order_index'], unique=False)
    op.create_index(op.f('ix_scenarioexecutionsteplog_endpoint_id'), 'scenarioexecutionsteplog', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_scenarioexecutionsteplog_ack_code'), 'scenarioexecutionsteplog', ['ack_code'], unique=False)
    op.create_table('scenario_ej_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entite_juridique_id', sa.INTEGER(), nullable=False),
    sa.Column('uf_hospitalisation_id', sa.INTEGER(), nullable=True),
    sa.Column('chambre_hospitalisation', sa.VARCHAR(length=20), nullable=True),
    sa.Column('lit_hospitalisation', sa.VARCHAR(length=20), nullable=True),
    sa.Column('medecin_hospitalisation_rpps', sa.VARCHAR(length=11), nullable=True),
    sa.Column('medecin_hospitalisation_nom', sa.VARCHAR(length=100), nullable=True),
    sa.Column('uf_consultation_id', sa.INTEGER(), nullable=True),
    sa.Column('chambre_consultation', sa.VARCHAR(length=20), nullable=True),
    sa.Column('medecin_consultation_rpps', sa.VARCHAR(length=11), nullable=True),
    sa.Column('medecin_consultation_nom', sa.VARCHAR(length=100), nullable=True),
    sa.Column('uf_urgences_id', sa.INTEGER(), nullable=True),
    sa.Column('chambre_urgences', sa.VARCHAR(length=20), nullable=True),
    sa.Column('lit_urgences', sa.VARCHAR(length=20), nullable=True),
    sa.Column('medecin_urgences_rpps', sa.VARCHAR(length=11), nullable=True),
    sa.Column('medecin_urgences_nom', sa.VARCHAR(length=100), nullable=True),
    sa.Column('uf_mutation_cible_id', sa.INTEGER(), nullable=True),
    sa.Column('chambre_mutation', sa.VARCHAR(length=20), nullable=True),
    sa.Column('lit_mutation', sa.VARCHAR(length=20), nullable=True),
    sa.Column('medecin_mutation_rpps', sa.VARCHAR(length=11), nullable=True),
    sa.Column('medecin_mutation_nom', sa.VARCHAR(length=100), nullable=True),
    sa.Column('medecin_traitant_rpps', sa.VARCHAR(length=11), nullable=True),
    sa.Column('medecin_traitant_nom', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['entite_juridique_id'], ['entitejuridique.id'], ),
    sa.ForeignKeyConstraint(['uf_consultation_id'], ['unitefonctionnelle.id'], ),
    sa.ForeignKeyConstraint(['uf_hospitalisation_id'], ['unitefonctionnelle.id'], ),
    sa.ForeignKeyConstraint(['uf_mutation_cible_id'], ['unitefonctionnelle.id'], ),
    sa.ForeignKeyConstraint(['uf_urgences_id'], ['unitefonctionnelle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_ej_config_entite_juridique_id'), 'scenario_ej_config', ['entite_juridique_id'], unique=1)
    op.create_table('patientcontextmapping',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('context_id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['endpointcontext.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venuecontextmapping',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('context_id', sa.INTEGER(), nullable=False),
    sa.Column('venue_id', sa.INTEGER(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['endpointcontext.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouvementcontextmapping',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('context_id', sa.INTEGER(), nullable=False),
    sa.Column('mouvement_id', sa.INTEGER(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['endpointcontext.id'], ),
    sa.ForeignKeyConstraint(['mouvement_id'], ['mouvement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
