"""Add status column to EntiteGeographique

Revision ID: f921c9819703
Revises: add_created_updated_to_identifiernamespace
Create Date: 2025-11-16 14:17:37.492074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f921c9819703'
down_revision: Union[str, Sequence[str], None] = 'add_created_updated_to_identifiernamespace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    for table in [
        'mouvementcontextmapping', 'patientcontextmapping', 'venuecontextmapping',
        'endpointcontext', 'scenarioexecutionrun', 'dossiercontextmapping', 'scenarioexecutionsteplog'
    ]:
        if table in inspector.get_table_names():
            op.drop_table(table)
    # Add status column as NOT NULL with default value for SQLite compatibility
    # op.add_column('entitegeographique', sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'INACTIVE', name='locationstatus'), nullable=False, server_default='ACTIVE'))  # Already exists, skip
    # SQLite does not support ALTER COLUMN for NOT NULL, so recreate the table
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = inspector.get_columns('entitegeographique')
    # Only recreate if 'name' is nullable
    name_col = next((col for col in columns if col['name'] == 'name'), None)
    if name_col and name_col['nullable']:
        op.rename_table('entitegeographique', 'entitegeographique_old')
        op.create_table('entitegeographique',
            sa.Column('id', sa.INTEGER(), nullable=False),
            sa.Column('name', sa.VARCHAR(), nullable=False),
            sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'INACTIVE', name='locationstatus'), nullable=False, server_default='ACTIVE'),
            sa.Column('category_code', sa.VARCHAR(), nullable=True),
            # ... add other columns as needed ...
            sa.PrimaryKeyConstraint('id')
        )
        # Copy data except rows with NULL name
        op.execute('''
            INSERT INTO entitegeographique (id, name, status, category_code)
            SELECT id, name, 'ACTIVE', category_code FROM entitegeographique_old WHERE name IS NOT NULL
        ''')
        op.drop_table('entitegeographique_old')
    op.alter_column('identifiernamespace', 'system',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('identifiernamespace', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('identifiernamespace', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('identifiernamespace', 'created_at')
    # op.drop_index('idx_messagelog_status_endpoint_created', table_name='messagelog')
    # op.drop_index('idx_mouvement_venue_when', table_name='mouvement')
    # op.drop_index('idx_mouvement_when', table_name='mouvement')
    # op.drop_index('idx_venue_dossier', table_name='venue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_venue_dossier', 'venue', ['dossier_id'], unique=False)
    op.create_index('idx_mouvement_when', 'mouvement', ['when'], unique=False)
    op.create_index('idx_mouvement_venue_when', 'mouvement', ['venue_id', 'when'], unique=False)
    op.create_index('idx_messagelog_status_endpoint_created', 'messagelog', ['status', 'endpoint_id', 'created_at'], unique=False)
    op.add_column('identifiernamespace', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.alter_column('identifiernamespace', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('identifiernamespace', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('identifiernamespace', 'system',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('entitegeographique', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('entitegeographique', 'status')
    op.create_table('scenarioexecutionsteplog',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.Column('step_id', sa.INTEGER(), nullable=True),
    sa.Column('endpoint_id', sa.INTEGER(), nullable=True),
    sa.Column('order_index', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('ack_code', sa.VARCHAR(), nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), nullable=True),
    sa.Column('error_message', sa.VARCHAR(), nullable=True),
    sa.Column('payload_excerpt', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['systemendpoint.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['scenarioexecutionrun.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['interopscenariostep.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_step_run_status', 'scenarioexecutionsteplog', ['run_id', 'status'], unique=False)
    op.create_index('ix_scenarioexecutionsteplog_step_id', 'scenarioexecutionsteplog', ['step_id'], unique=False)
    op.create_index('ix_scenarioexecutionsteplog_status', 'scenarioexecutionsteplog', ['status'], unique=False)
    op.create_index('ix_scenarioexecutionsteplog_run_id', 'scenarioexecutionsteplog', ['run_id'], unique=False)
    op.create_index('ix_scenarioexecutionsteplog_order_index', 'scenarioexecutionsteplog', ['order_index'], unique=False)
    op.create_index('ix_scenarioexecutionsteplog_endpoint_id', 'scenarioexecutionsteplog', ['endpoint_id'], unique=False)
    op.create_index('ix_scenarioexecutionsteplog_ack_code', 'scenarioexecutionsteplog', ['ack_code'], unique=False)
    op.create_table('dossiercontextmapping',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('context_id', sa.INTEGER(), nullable=False),
    sa.Column('dossier_id', sa.INTEGER(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['endpointcontext.id'], ),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarioexecutionrun',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scenario_id', sa.INTEGER(), nullable=False),
    sa.Column('endpoint_id', sa.INTEGER(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('total_steps', sa.INTEGER(), nullable=False),
    sa.Column('success_steps', sa.INTEGER(), nullable=False),
    sa.Column('error_steps', sa.INTEGER(), nullable=False),
    sa.Column('skipped_steps', sa.INTEGER(), nullable=False),
    sa.Column('dry_run', sa.BOOLEAN(), nullable=False),
    sa.Column('options_json', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['systemendpoint.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['interopscenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scenarioexecutionrun_status', 'scenarioexecutionrun', ['status'], unique=False)
    op.create_index('ix_scenarioexecutionrun_scenario_id', 'scenarioexecutionrun', ['scenario_id'], unique=False)
    op.create_index('ix_scenarioexecutionrun_finished_at', 'scenarioexecutionrun', ['finished_at'], unique=False)
    op.create_index('ix_scenarioexecutionrun_endpoint_id', 'scenarioexecutionrun', ['endpoint_id'], unique=False)
    op.create_index('ix_scenarioexecutionrun_dry_run', 'scenarioexecutionrun', ['dry_run'], unique=False)
    op.create_index('ix_run_scenario_status', 'scenarioexecutionrun', ['scenario_id', 'status'], unique=False)
    op.create_table('endpointcontext',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('endpoint_id', sa.INTEGER(), nullable=False),
    sa.Column('last_sequence_value', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['systemendpoint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venuecontextmapping',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('context_id', sa.INTEGER(), nullable=False),
    sa.Column('venue_id', sa.INTEGER(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['endpointcontext.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patientcontextmapping',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('context_id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['endpointcontext.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouvementcontextmapping',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('context_id', sa.INTEGER(), nullable=False),
    sa.Column('mouvement_id', sa.INTEGER(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['endpointcontext.id'], ),
    sa.ForeignKeyConstraint(['mouvement_id'], ['mouvement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
